insert into cidades(id_paises, cidade) values 
	(1, 'NOVA YORK'),
	(1, 'LOS ANGELES'),
	(1, 'CHICAGO'),
	(1, 'HOUSTON'),
	(2, 'PEQUIM'),
	(2, 'XANGAI'),
	(2, 'SHENZHEN'),
	(2, 'GUANGZHOU'),
	(3, 'TÓQUIO'),
	(3, 'OSAKA'),
	(3, 'NAGOYA'),
	(3, 'YOKOHAMA'),
	(4, 'BERLIM'),
	(4, 'HAMBURGO'),
	(4, 'MUNIQUE'),
	(4, 'COLÔNIA'),
	(5, 'LONDRES'),
	(5, 'MANCHESTER'),
	(5, 'BIRMINGHAM'),
	(5, 'GLASGOW'),
	(6, 'PARIS'),
	(6, 'LYON'),
	(6, 'MARSELHA'),
	(6, 'TOULOUSE'),
	(7, 'MUMBAI'),
	(7, 'DELHI'),
	(7, 'BANGALORE'),
	(7, 'CHENNAI'),
	(8, 'ROMA'),
	(8, 'MILÃO'),
	(8, 'NÁPOLES'),
	(8, 'TURIM'),
	(9, 'SÃO PAULO'),
	(9, 'RIO DE JANEIRO'),
	(9, 'BRASÍLIA'),
	(9, 'SALVADOR'),
	(10, 'TORONTO'),
	(10, 'MONTREAL'),
	(10, 'VANCOUVER'),
	(10, 'CALGARY'),
	(11, 'SEUL'),
	(11, 'BUSAN'),
	(11, 'INCHEON'),
	(11, 'DAEGU'),
	(12, 'SYDNEY'),
	(12, 'MELBOURNE'),
	(12, 'BRISBANE'),
	(12, 'PERTH'),
	(13, 'MOSCOU'),
	(13, 'SÃO PETERSBURGO'),
	(13, 'NOVOSIBIRSK'),
	(13, 'ECATERIMBURGO'),
	(14, 'MADRID'),
	(14, 'BARCELONA'),
	(14, 'VALÊNCIA'),
	(14, 'SEVILHA'),
	(15, 'CIDADE DO MÉXICO'),
	(15, 'GUADALAJARA'),
	(15, 'MONTERREY'),
	(15, 'PUEBLA'),
	(16, 'JACARTA'),
	(16, 'SURABAIA'),
	(16, 'BANDUNG'),
	(16, 'MEDAN'),
	(17, 'ISTAMBUL'),
	(17, 'ANCARA'),
	(17, 'IZMIR'),
	(17, 'BURSA'),
	(18, 'AMSTERDÃ'),
	(18, 'ROTTERDÃ'),
	(18, 'HAIA'),
	(18, 'UTRECHT'),
	(19, 'ZURIQUE'),
	(19, 'GENEBRA'),
	(19, 'BASILEIA'),
	(19, 'BERNA'),
	(20, 'RIAD'),
	(20, 'JEDDAH'),
	(20, 'MECA'),
	(20, 'MEDINA'),
	(21, 'CIDADE DO CABO'),
	(21, 'JOANESBURGO'),
	(21, 'DURBAN'),
	(21, 'PRETÓRIA'),
	(21, 'KRUGER NATIONAL PARK'),
	(21, 'PORT ELIZABETH'),
	(21, 'SUN CITY'),
	(21, 'STELLENBOSCH'),
	(22, 'BUENOS AIRES'),
	(22, 'BARILOCHE'),
	(22, 'MENDOZA'),
	(22, 'CÓRDOBA'),
	(22, 'USHUAIA'),
	(22, 'ROSÁRIO'),
	(22, 'SALTA'),
	(22, 'EL CALAFATE'),
	(23, 'LIMA'),
	(23, 'CUSCO'),
	(23, 'MACHU PICCHU'),
	(23, 'AREQUIPA'),
	(23, 'LAGO TITICACA'),
	(23, 'TRUJILLO'),
	(23, 'IQUITOS'),
	(23, 'NAZCA'),
	(24, 'LISBOA'),
	(24, 'PORTO'),
	(24, 'FARO'),
	(24, 'SINTRA'),
	(24, 'ÉVORA'),
	(24, 'COIMBRA'),
	(24, 'BRAGA'),
	(24, 'MADEIRA');