insert into paises(pais) values
	('ESTADOS UNIDOS'),
    ('CHINA'),
    ('JAPÃO'),
    ('ALEMANHA'),
    ('REINO UNIDO'),
    ('FRANÇA'),
    ('ÍNDIA'),
    ('ITÁLIA'),
    ('BRASIL'),
    ('CANADÁ'),
    ('COREIA DO SUL'),
    ('AUSTRÁLIA'),
    ('RÚSSIA'),
    ('ESPANHA'),
    ('MÉXICO'),
    ('INDONÉSIA'),
    ('TURQUIA'),
    ('PAÍSES BAIXOS'),
    ('SUÍÇA'),
    ('ARÁBIA SAUDITA'),
    ('ÁFRICA DO SUL'),
    ('ARGENTINA'),
    ('PERU'),
    ('PORTUGAL');